CREATE TABLE agent_properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  CONSTRAINT unique_agent_property UNIQUE (agent_id, property_id)
);

COMMENT ON TABLE agent_properties IS 'Mapping table between agents and properties they handle';
COMMENT ON COLUMN agent_properties.agent_id IS 'Reference to agent profile';
COMMENT ON COLUMN agent_properties.property_id IS 'Reference to managed property';